/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DELL
 */
public class MenuMakanan extends javax.swing.JFrame {

    /**
     * Creates new form MenuMakanan
     */
    public MenuMakanan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbxbaksokerikil = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        txtjumlah1 = new javax.swing.JTextField();
        cbxbaksobiasa = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        txtjumlah2 = new javax.swing.JTextField();
        cbxmie = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        txtjumlah3 = new javax.swing.JTextField();
        txtjumlah4 = new javax.swing.JTextField();
        cbxmiegoreng = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        txtjumlah5 = new javax.swing.JTextField();
        cbxsotoayam = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        txtjumlah6 = new javax.swing.JTextField();
        cbxesjeruk = new javax.swing.JCheckBox();
        jLabel12 = new javax.swing.JLabel();
        txtjumlah7 = new javax.swing.JTextField();
        cbxesteh = new javax.swing.JCheckBox();
        jLabel13 = new javax.swing.JLabel();
        txtjumlah8 = new javax.swing.JTextField();
        cbxesnutrisari = new javax.swing.JCheckBox();
        jLabel14 = new javax.swing.JLabel();
        txtjumlah9 = new javax.swing.JTextField();
        cbxlemontea = new javax.swing.JCheckBox();
        jLabel15 = new javax.swing.JLabel();
        txtjumlah10 = new javax.swing.JTextField();
        cbxkopi = new javax.swing.JCheckBox();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txapesan = new javax.swing.JTextArea();
        btnpesan = new javax.swing.JButton();
        btnreset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 255));

        jLabel1.setText("Menu Makanan :");

        jLabel2.setText("Harga :");

        jLabel3.setText("Jumlah :");

        jLabel4.setText("Menu Minuman :");

        jLabel5.setText("Harga :");

        jLabel6.setText("Jumlah :");

        cbxbaksokerikil.setText("Bakso Kerikil");
        cbxbaksokerikil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxbaksokerikilActionPerformed(evt);
            }
        });

        jLabel7.setText("Rp. 15.000");

        cbxbaksobiasa.setText("Bakso Biasa");

        jLabel8.setText("Rp. 15.000");

        cbxmie.setText("Mie Ayam");

        jLabel9.setText("Rp. 15.000");

        cbxmiegoreng.setText("Mie Goreng");

        jLabel10.setText("Rp. 20.000");

        cbxsotoayam.setText("Soto Ayam");

        jLabel11.setText("Rp. 20.000");

        txtjumlah6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjumlah6ActionPerformed(evt);
            }
        });

        cbxesjeruk.setText("Es Jeruk");

        jLabel12.setText("Rp. 5.000");

        cbxesteh.setText("Es Teh");

        jLabel13.setText("Rp. 5.000");

        cbxesnutrisari.setText("Es Nutrisari");

        jLabel14.setText("Rp. 5.000");

        cbxlemontea.setText("Lemon Tea");

        jLabel15.setText("Rp. 5.000");

        cbxkopi.setText("Kopi");

        jLabel16.setText("Rp. 5.000");

        jLabel17.setText("Menu Yang Di Pesan :");

        txapesan.setColumns(20);
        txapesan.setRows(5);
        jScrollPane1.setViewportView(txapesan);

        btnpesan.setText("Pesan");
        btnpesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpesanActionPerformed(evt);
            }
        });

        btnreset.setText("Reset");
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxbaksokerikil)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel7))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(txtjumlah1))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbxbaksobiasa)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbxmie)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbxmiegoreng)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel10))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbxsotoayam)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel11)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtjumlah5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtjumlah4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtjumlah2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtjumlah3))))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel5)
                        .addGap(29, 29, 29))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(cbxesnutrisari)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel14))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbxesjeruk)
                                    .addComponent(cbxesteh))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel12)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbxlemontea)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel15))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbxkopi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel16)))
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtjumlah6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                        .addComponent(txtjumlah7, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtjumlah8, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtjumlah9, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtjumlah10, javax.swing.GroupLayout.Alignment.LEADING)))
                .addGap(132, 132, 132))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(btnpesan)
                        .addGap(62, 62, 62)
                        .addComponent(btnreset)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(txtjumlah1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(cbxbaksokerikil)
                                        .addComponent(jLabel7))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cbxesjeruk)
                                .addComponent(jLabel12))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtjumlah6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(txtjumlah2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbxbaksobiasa)
                        .addComponent(jLabel8))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(txtjumlah7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cbxesteh, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(txtjumlah8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbxmie)
                        .addComponent(jLabel9)
                        .addComponent(txtjumlah3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cbxesnutrisari))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtjumlah4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxlemontea)
                            .addComponent(jLabel15)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbxmiegoreng)
                        .addComponent(jLabel10))
                    .addComponent(txtjumlah9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtjumlah5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxkopi)
                            .addComponent(txtjumlah10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbxsotoayam)
                        .addComponent(jLabel11))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16)))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnpesan)
                    .addComponent(btnreset))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxbaksokerikilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxbaksokerikilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxbaksokerikilActionPerformed

    private void btnpesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpesanActionPerformed
        // TODO add your handling code here:
        String tampil;
        tampil = "";
        int bayar = 0;
        if(cbxbaksokerikil.isSelected()) {
            int jumlah=Integer.parseInt(txtjumlah1.getText());
            int total;
            total=jumlah*15000;
            bayar=bayar+total;
            tampil +=cbxbaksokerikil.getText()+" Rp.15.000"+" x "+jumlah+" = "+total+"\n";
        }if(cbxbaksobiasa.isSelected()) {
            int jumlah=Integer.parseInt(txtjumlah2.getText());
            int total;
            total=jumlah*15000;
            bayar=bayar+total;
            tampil +=cbxbaksobiasa.getText()+" Rp.15.000"+" x "+jumlah+" = "+total+"\n";
        }if(cbxmie.isSelected()) {
            int jumlah=Integer.parseInt(txtjumlah3.getText());
            int total;
            total=jumlah*15000;
            bayar=bayar+total;
            tampil +=cbxmie.getText()+" Rp.15.000"+" x "+jumlah+" = "+total+"\n";
        }if(cbxmiegoreng.isSelected()) {
            int jumlah=Integer.parseInt(txtjumlah4.getText());
            int total;
            total=jumlah*20000;
            bayar=bayar+total;
            tampil +=cbxmiegoreng.getText()+" Rp.20.000"+" x "+jumlah+" = "+total+"\n";
        }if(cbxsotoayam.isSelected()) {
            int jumlah=Integer.parseInt(txtjumlah5.getText());
            int total;
            total=jumlah*20000;
            bayar=bayar+total;
            tampil +=cbxsotoayam.getText()+" Rp.20.000"+" x "+jumlah+" = "+total+"\n";
        }if(cbxesjeruk.isSelected()) {
            int jumlah=Integer.parseInt(txtjumlah6.getText());
            int total;
            total=jumlah*5000;
            bayar=bayar+total;
            tampil +=cbxesjeruk.getText()+" Rp.5.000"+" x "+jumlah+" = "+total+"\n";
        }if(cbxesteh.isSelected()) {
            int jumlah=Integer.parseInt(txtjumlah7.getText());
            int total;
            total=jumlah*5000;
            bayar=bayar+total;
            tampil +=cbxesteh.getText()+" Rp.5.000"+" x "+jumlah+" = "+total+"\n";
        }if(cbxesnutrisari.isSelected()) {
            int jumlah=Integer.parseInt(txtjumlah8.getText());
            int total;
            total=jumlah*5000;
            bayar=bayar+total;
            tampil +=cbxesnutrisari.getText()+" Rp.5.000"+" x "+jumlah+" = "+total+"\n";
        }if(cbxlemontea.isSelected()) {
            int jumlah=Integer.parseInt(txtjumlah9.getText());
            int total;
            total=jumlah*5000;
            bayar=bayar+total;
            tampil +=cbxlemontea.getText()+" Rp.5.000"+" x "+jumlah+" = "+total+"\n";
        }if(cbxkopi.isSelected()) {
            int jumlah=Integer.parseInt(txtjumlah10.getText());
            int total;
            total=jumlah*5000;
            bayar=bayar+total;
            tampil +=cbxkopi.getText()+" Rp.5.000"+" x "+jumlah+" = "+total+"\n";
        }
        txapesan.setText(tampil+"="+"n"+"Total Bayar ="+bayar);
    }//GEN-LAST:event_btnpesanActionPerformed

    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
        // TODO add your handling code here:
        txtjumlah1.setText("");
        txtjumlah2.setText("");
        txtjumlah3.setText("");
        txtjumlah4.setText("");
        txtjumlah5.setText("");
        txtjumlah6.setText("");
        txtjumlah7.setText("");
        txtjumlah8.setText("");
        txtjumlah9.setText("");
        txtjumlah10.setText("");
        txapesan.setText("");
    }//GEN-LAST:event_btnresetActionPerformed

    private void txtjumlah6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjumlah6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtjumlah6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuMakanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuMakanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuMakanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuMakanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuMakanan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnpesan;
    private javax.swing.JButton btnreset;
    private javax.swing.JCheckBox cbxbaksobiasa;
    private javax.swing.JCheckBox cbxbaksokerikil;
    private javax.swing.JCheckBox cbxesjeruk;
    private javax.swing.JCheckBox cbxesnutrisari;
    private javax.swing.JCheckBox cbxesteh;
    private javax.swing.JCheckBox cbxkopi;
    private javax.swing.JCheckBox cbxlemontea;
    private javax.swing.JCheckBox cbxmie;
    private javax.swing.JCheckBox cbxmiegoreng;
    private javax.swing.JCheckBox cbxsotoayam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txapesan;
    private javax.swing.JTextField txtjumlah1;
    private javax.swing.JTextField txtjumlah10;
    private javax.swing.JTextField txtjumlah2;
    private javax.swing.JTextField txtjumlah3;
    private javax.swing.JTextField txtjumlah4;
    private javax.swing.JTextField txtjumlah5;
    private javax.swing.JTextField txtjumlah6;
    private javax.swing.JTextField txtjumlah7;
    private javax.swing.JTextField txtjumlah8;
    private javax.swing.JTextField txtjumlah9;
    // End of variables declaration//GEN-END:variables
}
